---
- name: Delete DNS record on Windows DNS server
  hosts: DNSServername
  gather_facts: False
  vars:
    device_hostname: ''
    DNS_domain: ''

  tasks:
  - name: Remove static record
    win_dns_record:
      name: {{ device_hostname }}
      type: "A"
      state: absent
      zone: {{ DNS_domain }}