---
- name: Mitigating Microsoft CVE-2020-1350.
  hosts: all
  gather_facts: False

  tasks:
    - name: Backing up Registry settings for HKLM
      win_command: REG EXPORT HKLM C:\HKLM.Reg /y
      register: reg_save

    - name: Changing registry settings for DNS parameters
      win_regedit:
        path: HKLM:\\SYSTEM\CurrentControlSet\Services\DNS\Parameters
        name: TcpReceivePacketSize 
        data: 0xFF00
        type: dword

    - name: Displaying current value for DNS parameters
      win_reg_stat:
        path: HKLM:\\SYSTEM\CurrentControlSet\Services\DNS\Parameters
        name: TcpReceivePacketSize
      register: current_value

    - name: restarting DNS service
      win_service:
        name: DNS
        state: Restarted
        start_mode: auto