---
- hosts: localhost # Network devices don't have python. Processing must be done on localhost
  connection: local
  gather_facts: no # gather_facts are only for server OS's. Network facts require a module
  vars:
    tenant: '' # Best practice, declare vars at top of playbook. This makes it easy to see a list or required variables
    description: ''
    state: ''

  collections:
    - cisco.aci # Best practice is to declare your collection within the playbook

  tasks:

    #- name: Setting up provider values
    #   set_fact:
    #    provider:
    #     host: "{{ host }}"
    #     port: "{{ port }}"
    #     username: "{{ username }}"
    #     password: "{{ password }}"

    # Optionally you can set the provider values. Useful if using many aci modules in the 
    # same playbook. Then it only needs to be declared once at the top

    - name: Ensure tenant customer-xyz exists
      cisco.aci.aci_tenant: # Best practice is to use full name space
        host: "{{ aci_host }}"     # host, username and password are supplied by custom credential
        #port: "{{ port }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password }}"

        tenant: "{{ aci_tenant }}"
        description: "{{ description }}"
        state: "{{ state }}" # present, absent or query
  # Avoid hard coding values. The more variables you use, the more shareable the playbook.