---
- name: Start Backup of ios Devices
  hosts: all
  connection: network_cli
  become: yes
  gather_facts: no
  vars:
    ansible_network_os: ios
    backup_path: /var/lib/awx/Networking_Tools/Config_Backups/

  tasks:
    - name: Backup the config of {{inventory_hostname}} to {{backup_path}}
      ios_config:
        backup: yes
        backup_options:
          dir_path: "{{backup_path}}"
    
    - name: Backup with register variable
      ios_config:
        backup: yes
      register: config_output

    - name: Rename backup
      copy:
        src: "{{config_output.backup_path}}"
        dest: "{{backup_path}}{{inventory_hostname}}.config"