---
- name: Play to create new user and upload key
  hosts: all
  gather_facts: false
  connection: network_cli
  #vars:
    #ansible_network_os: ios

  tasks:

  - name: create ssh keys for user {{ user }}
    command: echo -e 'y\n'|ssh-keygen -q -t rsa -f /incoming/{{ user }} -C "" -N ""
    register: output
  - debug: var=output.stdout_lines

  - name: Adding new user {{ user }} and uploading key now...
    ios_user:
      name: "{{ user }}"
      nopassword: True
      sshkey: "{{ lookup('file', '/incoming/{{ user }}.pub') }}"
      privilege: 15
      state: present
# https://docs.ansible.com/ansible/2.9/modules/ios_user_module.html#ios-user-module