---
- name: Get Device Facts - Install Juniper.junos Galaxy first! "ansible-galaxy install Juniper.junos"
  hosts: rtr3
  roles:
    - Juniper.junos 
  connection: network_cli
  gather_facts: true

  tasks:
    - name: Checking NETCONF connectivity.
      wait_for: 
        host: "{{ ansible_hostname }}"
        port: 830 
        timeout: 5

    - name: Retrieving information from devices running Junos OS
      juniper_junos_facts:
        host: "{{ ansible_hostname }}"

    - name: Print version
      debug:
        var: junos.version