# basic_networking_config.yml
#
# DESCRIPTION
# Example playbook that will configure basic networking and set default password for the admin user. In particular this
# script will:
# - update admin password with new password using SSH
# - create layer 3 trust and untrust zones
# - configure eth1/1 with DHCP and add it to untrust zone
# - configure eth1/2 with DHCP and add it to trust zone
# - set primary DNS server to Google's 8.8.8.8
# - set NTP servers to 0.us.pool.ntp.org and 1.us.pool.ntp.org
#
# The first call uses SSH protocol with private key. This is a typical example of what user has to do in order to
# provision FW in AWS.
#
# REQUIREMENTS
# Ansible version 2.9+
# pan-python
# ansible-galaxy install PaloAltoNetworks.paloaltonetworks

---
- hosts: all
  connection: local
  gather_facts: False

  roles:
    - paloaltonetworks.paloaltonetworks
    - ansible-network.network-engine

  tasks: 

   # - name: change user password using ssh protocol
    #  panos_admpwd:
     #   ip_address: "{{ mgmt_ip }}"
      #  username: "{{admin_username}}"
       # newpassword: "{{admin_password}}"
        #key_filename: "{{key_name}}"

    - name: configure ethernet1/1
      panos_interface:
        ip_address: "{{mgmt_ip}}"
        username: "{{admin_username}}"
        password: "{{admin_password}}"
        if_name: "ethernet1/1"
        zone_name: "untrust"
        create_default_route: "yes"
        commit: False

    - name: configure ethernet1/2
      panos_interface:
        ip_address: "{{mgmt_ip}}"
        username: "{{admin_username}}"
        password: "{{admin_password}}"
        if_name: "ethernet1/2"
        zone_name: "trust"
        create_default_route: "no"
        commit: False

    - name: set dns and ntp
      panos_mgtconfig:
        ip_address: "{{mgmt_ip}}"
        username: "{{admin_username}}"
        password: "{{admin_password}}"
        dns_server_primary: "8.8.8.8"
        #ntp_server_primary: "0.us.pool.ntp.org"
        #ntp_server_secondary: "1.us.pool.ntp.org"
        #timezone: "US/Pacific"
        #login_banner: "Secure environment"
        commit: True