---
- hosts: all
  connection: local
  gather_facts: False

  collections:
    - paloaltonetworks.paloaltonetworks

  tasks: 

    - name: change user password using ssh protocol
      paloaltonetworks.panos.panos_admpwd:
        ip_address: "{{ mgmt_ip }}"
        username: "{{admin_username}}"
        newpassword: "{{admin_password}}"
        key_filename: "{{key_name}}"