# Cannot get this to work. I have the private key on Tower in the path described
# No matter what permissions I put on the key file I get permission denied for the key
# I have two credentials defined in my template. A machine cred with username, password and key
# plus a tower credential.

---
- hosts: all
  connection: local
  gather_facts: False

  collections:
    - paloaltonetworks.paloaltonetworks

  tasks: 

    - name: change user password using ssh protocol
      panos_admpwd:
        ip_address: "{{ ansible_host }}"
        username: "{{ admin_username }}"
        newpassword: "{{ admin_password }}"
        key_filename: "/home/ec2-user/aws-west-ml.pem"
      #register: result
      #until: not result|failed
      #retries: 10
      #delay: 30