---
- hosts: all
  connection: local
  gather_facts: False

  collections:
    - paloaltonetworks.paloaltonetworks

  tasks: 

    - name: change user password using ssh protocol
      panos_admpwd:
        ip_address: "{{ ansible_host }}"
        username: "{{ admin_username }}"
        newpassword: "{{ admin_password }}"
        key_filename: "/home/ec2-user/aws-west-ml.pem"