---
- hosts: all
  become: yes
  become_user: sudo

  tasks:
      - name: Check TimeZone for device {{ ipv4_host }} 
        shell: timedatectl | grep -i 'time zone'| awk '{ print $3}'
        register: TimeZoneOUT
      - debug: msg={{TimeZoneOUT.stdout}}

      - name: Set timezone when is not America/Los_Angeles
        shell: timedatectl set-timezone America/Los_Angeles
        when: TimeZoneOUT.stdout != 'America/Los_Angeles'