---
- name: Check Linux performance in less than 30 seconds
  hosts: all
  become: true
  become_user: root
  become_method: sudo

  tasks:
    - name: Command will trigger dmesg
      shell:
        cmd: dmesg -T >> /tmp/{{ansible_host}}_performance_analysis.txt

    - name: Command will run vmstat for 3 seconds
      shell:
        cmd: vmstat 1 3 >> /tmp/{{ansible_host}}_performance_analysis.txt
  
    - name: Command will run mpstat for 3 seconds
      shell:
        cmd: mpstat -P ALL 1 3 >> /tmp/{{ansible_host}}_performance_analysis.txt
 
    - name: Command will run pidstat for 3 seconds
      shell:
        cmd: pidstat 1 3 >> /tmp/{{ansible_host}}_performance_analysis.txt

    - name: Command will run pidstat for 3 seconds
      shell:
        cmd: iostat -xz 1 3 >> /tmp/{{ansible_host}}_performance_analysis.txt

    - name: Command will run "free -m"
      shell:
        cmd: free -m >> /tmp/{{ansible_host}}_performance_analysis.txt

    - name: Command will run sar -n DEV 1 for 3 seconds
      shell:
        cmd: sar -n DEV 1 3 >> /tmp/{{ansible_host}}_performance_analysis.txt

    - name: Command will run sar -n TCP,ETCP 1 for 3 seconds
      shell:
        cmd: sar -n TCP,ETCP 1 3 >> /tmp/{{ansible_host}}_performance_analysis.txt

    - name: Command will run top -b -n for 3 seconds
      shell:
        cmd: top -b -n 3 >> /tmp/{{ansible_host}}_performance_analysis.txt