---
- hosts: all
  become: true
  become_user: root
  vars:
    rpz_zone: '/var/named/db.rpz.local'
    rpz_new_domain: ''

  tasks:
    - name: Get date and time
      shell: date +%Y%m%d%H%M%S
      register: todaydate

    - name: Replace RPZ zone serial number
      lineinfile: 
        path: "{{ rpz_zone }}" 
        regexp: '^(.*); serial(.*)$' 
        line: '                                        {{ todaydate.stdout }}; serial'
        backrefs: yes
        
    - name: Add the new domain "{{ rpz_new_domain }}" line if it does not exist
      lineinfile:
        path: "{{ rpz_zone }}"
        line: "*.{{ rpz_new_domain}}        CNAME       ."
        state: present
        backup: yes
      register: new_zone_record

    - name: Reload bind named
      shell: service named reload
      register: bind_reload