---
- name: Get snapshot info
  hosts: localhost
  connection: local
  vars:
    gcp_project: linen-jet-264723
    gcp_cred_kind: serviceaccount
    label: ''
    zone: ''
    disk_name: 'disk-mark1'

  tasks:
    - name: get info on a disk
      gcp_compute_disk_info:
        zone: us-central1-a
        filters:
        - name = "{{ disk_name }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
      register: disk
         
    - include: create_snapshot.yml
      when: disk.resources #[0].creationTimestamp | < 1800