---
- name: BIG-IP SETUP
  hosts: lb
  connection: local
  gather_facts: false
  
    

  tasks:

  - name: CREATE NODES
    bigip_node:
      provider:
        server: "{{ansible_host}}"
        server_port: "{{ tcp_port }}" # 443 for on-prem. Must be 8443 in public cloud
        validate_certs: false
      host: "{{hostvars[item].ansible_host}}"
      state: "{{state}}"
      name: "{{hostvars[item].inventory_hostname}}"
    loop: "{{ groups['tag_ansible_group_jboss'] }}"
    #loop: "{{ groups['tag_Name_mlowcher_jboss_demo'] }}"

