---
- name: BIG-IP SETUP
  hosts: lb
  connection: local
  gather_facts: false

  tasks:

  - name: Create or delete virtual server
    bigip_virtual_server:
      provider:
        server: "{{ansible_host}}"
        user: "{{ansible_user}}"
        password: "{{ansible_ssh_pass}}"
        server_port: 8443
        validate_certs: false
      name: "{{vs_name}}"
      #destination: "{{ec2_private_ip_address}}"
      destination: "{{private_ip}}"
      port: "443"
      state: "{{state}}"
      enabled_vlans: "all"
      all_profiles: ['coolApp_http', 'coolApp_clientssl', 'coolApp_tcp', 'oneconnect']
      pool: "http_pool"
      snat: "Automap"

  - name: Create or delete a HTTP Redirect Virtual Server
    bigip_virtual_server:
      provider:
        server: "{{ansible_host}}"
        user: "{{ansible_user}}"
        password: "{{ansible_ssh_pass}}"
        server_port: 8443
        validate_certs: false
      name: coolApp_redirect
      #destination: "{{ec2_private_ip_address}}"
      destination: "{{private_ip}}"
      port: "80"
      state: "{{state}}"
      enabled_vlans: "all"
      all_profiles:
       - http
      all_rules:
       - _sys_https_redirect
