---
- name: Create a clientssl profile
  hosts: lb
  connection: local
  gather_facts: false

  tasks:

    - name: Create a client SSL profile with a cert/key/chain setting
      bigip_profile_client_ssl:
        state: "{{state}}"
        name: "{{profile_name}}"
        ciphers: "!SSLv3:ECDHE+AES-GCM+SHA256:ECDHE-RSA-AES128-CBC-SHA"
        cert_key_chain:
          - cert: f5test
            key: f5test
            #chain: f5test
        provider:
          server: "{{ansible_host}}"
          user: "{{ansible_user}}"
          password: "{{ansible_ssh_pass}}"
          server_port: 8443
          validate_certs: false
      delegate_to: localhost
