---
# This playbook will edit the httpd on F5 to create a workaround for CVE-2020-5902.
# Please refer to:
# https://support.f5.com/csp/article/K52145254 for information regarding this critical exploit.
# There is currently an issue with restarting the httpd daemon after sending a curl command.
# Please refer to:
# K13292945: httpd failing to start after restarting the service using the iControl REST API
# https://support.f5.com/csp/article/K13292945
# Until this is fixed use "Restarting HTTPD daemon with tmsh".

- name: Mitigate CVE-2020-5902
  hosts: all
  connection: local
  gather_facts: false

  tasks:
    - name: Editing HTTPD
      raw: curl -ku "{{ansible_user}}":"{{ansible_ssh_pass}}" -k https://"{{ansible_host}}":8443/mgmt/tm/sys/httpd -H content-type:application/json -X PATCH -d '{"include":"\n <LocationMatch \\\";\\\">\n Redirect 404 /\n </LocationMatch>\n <LocationMatch \\\"hsqldb\\\">\n Redirect 404 /\n </LocationMatch>\n "}'
  
    - name: Saving HTTPD change
      bigip_command:
        commands: save sys config
        provider:
          server: "{{ansible_host}}"
          user: "{{ansible_user}}"
          password: "{{ansible_ssh_pass}}"
          server_port: 8443 # port 8443 for public cloud, port 443 for on-prem
          validate_certs: false
